"""initial commit

Revision ID: 528f9b0755d7
Revises: 142736b3a845
Create Date: 2022-04-14 07:33:46.832679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '528f9b0755d7'
down_revision = '142736b3a845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vaccine_cards', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
